export const pt = {
  REGISTER_FAILED: "Falha ao Registrar",
  LOGIN_FAILED: "Falha ao Logar",
  INCORRECT_PAYLOAD: "Payload Incorreto",
  USER_NOT_FOUND: "Usuario não encontrado",
  USER_DUPLICATED: "Usuario Duplicado",
  AUTHORIZATION_NOT_FOUND: "Authorização não encontrada",
  TOKEN_NOT_FOUND: "Token não encontrado",
  ERROR_TO_SAVE_FILE: "erro ao salvar o arquivo",
  FILE_SIZE_LIMIT_EXCEEDED: "O arquivo é muito grande. O tamanho máximo é 5MB.",
  FILE_REQUIRED: "Arquivo é obrigatório",
  FOLDER_NAME_REQUIRED: "Nome da pasta é obrigatório",
  FOLDER_ALREADY_EXISTS: "Pasta já existe",
  FOLDER_NOT_FOUND: "Pasta não encontrada",
  FILE_NOT_FOUND: "Arquivo não encontrado",
};
